name: rtp-tutorial
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2.7
    - pip
    - future
    - numpy
    - scipy
    - matplotlib>=1.5
    - basemap
    - pillow
    - jupyter
    - seaborn
    - fatiando=0.4
    - pandoc
